---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  markdownlint:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
      - .js
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - XXX
      - HACK
ratings:
  paths:
  - "**.js"
  - "**.md"
  - "**.es6"
  - "**.jsx"
